--- 
networks: 
  elasticsearch: ~
services: 
  elasticsearch: 
    container_name: elasticsearch8
    environment:
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=test
      - xpack.security.enabled=true
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.12.0"
    networks: 
      - elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
version: "2"
