--- 
networks: 
  elasticsearch: ~
services: 
  elasticsearch: 
    container_name: elasticsearch
    environment: 
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.29"
    networks: 
      - elasticsearch
    ports: 
      - "9200:9200"
      - "9300:9300"
version: "2"
