---
networks:
  postgres: ~
services:
  postgresql:
    container_name: postgres-image-service
    image: "postgres:11.22-alpine"
    networks:
      - postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=changethispassword
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
version: "2"
