pluginManagement {
    repositories {
        mavenLocal()
        maven { url "https://nexus.ala.org.au/content/groups/public/" }
        mavenCentral()
        maven { url "https://repo.grails.org/grails/core/" }
        gradlePluginPortal()
    }
}

rootProject.name = 'image-project'

include 'image-service'
include 'image-utils'

// Our Grails App doesn't support Java 25 yet, so don't bother with the FFM modules for now.

//// Conditionally include FFM modules for Java 22+
//if (JavaVersion.current().isCompatibleWith(JavaVersion.VERSION_22)) {
//    include 'image-service-ffm'
//    include 'image-service-vips-ffm'
//}
