AWSTemplateFormatVersion: '2010-09-09'

Description: Base resources for the Images service

Parameters:
  pBuild:
    Type: String
    Description: The build number
  pBackupBucket:
    Type: String
    Description: The backup bucket
  pCleanBranch:
    Type: String
    Description: The clean branch, can be used in resource names
  pEnvironment:
    Type: String
    Description: The AWS environment this belongs to
  pProductComponent:
    Type: String
    Description: The product component
  pProductName:
    Type: String
    Description: The name of the product
  pOidcConnectProvider:
    Type: String
    Description: The OIDC connect provider
  pClusterOidcIssuerUrl:
    Type: String
    Description: The OIDC issuer URL for the cluster
  pCognitoStackName:
    Type: String
    Description: The name of the Cognito stack
  pAppClientDomain:
    Type: String
    Description: The domain for the app client
  pSecretName:
    Type: String
    Description: The name of the secret

Conditions:

  IsDev: !Equals
    - !Ref pEnvironment
    - development
  NotProd: !Not
    - !Equals
      - !Ref pEnvironment
      - production
  IsFirstBuild: !Equals [!Ref pBuild, "1"]

Resources:

  ImagesRepository:
    Type: AWS::ECR::Repository
    Properties:
      EmptyOnDelete: !If [ NotProd, true, false ]
      EncryptionConfiguration:
        EncryptionType: AES256
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: !Sub
                         - ${pProductName}-${ResourceName}
                         - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Sid: AllowPublicPull
            Effect: Allow
            Principal: '*'
            Action:
              - 'ecr:GetDownloadUrlForLayer'
              - 'ecr:BatchGetImage'
              - 'ecr:BatchCheckLayerAvailability'
      Tags:
        - Key: Environment
          Value: !Ref pEnvironment
        - Key: Branch
          Value: !Ref pCleanBranch

  ImagesRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
              {
                  "Effect": "Allow",
                  "Principal": {
                      "Federated": "${pOidcConnectProvider}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                      "StringEquals": {
                                        "${pClusterOidcIssuerUrl}:sub": "system:serviceaccount:${pProductName}:images-service-account",
                                        "${pClusterOidcIssuerUrl}:aud": "sts.amazonaws.com"
                      }
                  }
              },
              {
                "Effect": "Allow",
                "Principal": {
                  "Service":  "ec2.amazonaws.com"
                
                },
                "Action": "sts:AssumeRole"
              }
          ]
        }
      Description: !Sub 'Ec2 instance profile role for ${AWS::StackName} ${pEnvironment} build ${pBuild}'
      ManagedPolicyArns:
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/cpt/cptSSMInstanceCoreCloudWatchPatch
      Policies:
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - 'secretsmanager:getsecretvalue'
              Resource:
                - !Sub ${ImagesSecret}-??????
          PolicyName: secrets
        - PolicyDocument:
            Version: "2012-10-17"
            Statement:
            - Effect: Allow
              Action:
                - s3:DeleteObject
                - s3:DeleteObjectVersion
                - s3:GetBucketLocation
                - s3:GetObject
                - s3:ListBucket
                - s3:PutObject
              Resource:
                - !Sub arn:aws:s3:::${pBackupBucket}
                - !Sub arn:aws:s3:::${pBackupBucket}/*
          PolicyName: backups
      RoleName: !Sub '${AWS::StackName}--${pEnvironment}--${pBuild}'
      Tags:
        - Key: Name
          Value: !Sub 
              - ${pProductName}-${ResourceName}
              - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
 

  ImagesSecret:
    Type: AWS::SecretsManager::Secret
    Condition: IsFirstBuild
    Properties:
      Name: !Sub ${pSecretName}
      Description: !Sub Images app ${pEnvironment} secrets
      SecretString: !If
        - IsFirstBuild
        - |
          {
             "db-password" : ""
          }
        - !Ref "AWS::NoValue"

  AppClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 60
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - email
        - openid
        - profile
        - ala/roles
        - ala/attrs
      AuthSessionValidity: 3
      CallbackURLs:
        - !Sub "https://${pAppClientDomain}/callback?client_name=OidcClient"
      ClientName: !Sub
        - ${pProductName}-${ResourceName}
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      DefaultRedirectURI: !Sub "https://${pAppClientDomain}/callback?client_name=OidcClient"
      EnablePropagateAdditionalUserContextData: True
      EnableTokenRevocation: True
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: True
      IdTokenValidity: 60
      LogoutURLs:
        - !Sub "https://${pAppClientDomain}"
        - !Sub "https://${pAppClientDomain}/"
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
        - AAF
        - SignInWithApple
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      UserPoolId: !ImportValue
        Fn::Sub: ${pCognitoStackName}-UserPoolId

  AppClientImagesServer:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 60
      AllowedOAuthFlows:
        - client_credentials
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthScopes:
        - ala/internal
        - ala/attrs
        - users/read
      AuthSessionValidity: 3
      CallbackURLs:
        - !Sub "https://${pAppClientDomain}/callback?client_name=OidcClient"
      ClientName: !Sub
        - ${pProductName}-${ResourceName}-server-to-server
        - ResourceName: !If [ IsDev, !Ref pCleanBranch, !Ref pEnvironment ]
      DefaultRedirectURI: !Sub "https://${pAppClientDomain}/callback?client_name=OidcClient"
      EnablePropagateAdditionalUserContextData: True
      EnableTokenRevocation: True
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      GenerateSecret: True
      IdTokenValidity: 60
      LogoutURLs:
        - !Sub "https://${pAppClientDomain}"
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 30
      SupportedIdentityProviders:
        - COGNITO
        - Facebook
        - Google
        - AAF
        - SignInWithApple
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days
      UserPoolId: !ImportValue
        Fn::Sub: ${pCognitoStackName}-UserPoolId

Outputs:

  ImagesRepositoryArn:
    Description: The ECR repository ARN for the Images service
    Value: !GetAtt ImagesRepository.Arn

  ImagesRepositoryName:
    Description: The ECR repository ARN for the Images service
    Value: !Ref ImagesRepository

  ImagesRepositoryUri:
    Description: The ECR repository URI for the Images service
    Value: !GetAtt ImagesRepository.RepositoryUri
    Export:
      Name: !Sub ${AWS::StackName}-ImagesRepositoryUri

  ImagesSecret:
    Description: The Secrets name for Images
    Value: !Ref ImagesSecret

  ImagesRoleArn:
    Description: The role ARN for the Images service
    Value: !GetAtt ImagesRole.Arn

  ImagesAppClient:
    Description: The app client for the Image service
    Value: !Ref AppClient

  ImagesServerToServerAppClient:
    Description: The app client for the Image service
    Value: !Ref AppClientImagesServer