openapi: 3.0.1
info:
  title: Images REST services
  description: REST services for interacting with the images webapp
  termsOfService: https://www.ala.org.au/terms
  contact:
    name: Support
    email: support@ala.org.au
  license:
    name: Mozilla Public License 1.1
    url: https://www.mozilla.org/en-US/MPL/1.1/
  version: "@info.app.version@"
servers:
  - url: http://devt.ala.org.au:8080
paths:
  "/ws/image/{imageId}":
    get:
      tags:
        - images
      summary: Get Image Info
      description: Get Image Info
      operationId: Get Image Info
      responses:
        '200':
          description: Get Image Info