version: 0.2

env:
  shell: bash
  variables:
    JAVA_TOOL_OPTIONS: -Dhttps.protocols=TLSv1.2
  secrets-manager:
    DOCKER_USERNAME: ala-secrets-production:dockerhub-username
    DOCKER_PASSWORD: ala-secrets-production:dockerhub-password

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo loading all exported vars..
      - set -a ; source env.txt ; set +a
      - echo Installing dependencies...
      - cat /etc/lsb-release
      - apt update -y
        && apt-get install -y apt-transport-https ca-certificates software-properties-common build-essential pkg-config libvips-dev libglib2.0-dev
      - curl -s "https://get.sdkman.io" | bash
      - chmod a+x /root/.sdkman/bin/sdkman-init.sh
      - GRAILS_VERSION=$(grep '^grailsVersion=' gradle.properties | cut -d'=' -f2)
        && echo "GRAILS_VERSION=$GRAILS_VERSION"
        && source /root/.sdkman/bin/sdkman-init.sh && sdk install grails "$GRAILS_VERSION" /root/.sdkman/candidates/grails/$GRAILS_VERSION
      - java -version
      - echo Logging in to Docker Hub...
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
      - export GRADLE_OPTS="-Dgrails.env=travis"

  build:
    commands:
      - echo Build started on $(date)
      - echo Building the project...
      - chmod 666 /var/run/docker.sock
      - useradd -ms /bin/bash postgresuser
      - echo "Non-root user 'postgresuser' created"
      - chown -R postgresuser:postgresuser /tmp
      - chown -R postgresuser .
      - su - postgresuser -c "cd $(pwd) && exec ./gradlew clean build"
      - ./gradlew bootJar

  post_build:
    commands:
      - echo Post-build phase...
      - echo Build completed on $(date)
      - echo Building the Docker image...
      - export DOCKER_BUILDKIT=1
      - docker pull $ECR_REPO:latest
      - docker build --cache-from $ECR_REPO:latest --build-arg BUILDKIT_INLINE_CACHE=1 -t ala-images .
      - echo Tagging the Docker image...
      - echo build tag is $BUILD_TAG
      - echo tagging
      - docker tag ala-images:latest $ECR_REPO:$BUILD_TAG
      - docker tag ala-images:latest $ECR_REPO:latest
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $ECR_REPO:$BUILD_TAG
      - docker push $ECR_REPO:latest
      - echo Cleaning up LocalStack...
      - docker rm -f localstack || true


cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
    - '/root/.sdkman/candidates/grails/**/*'
    - '/root/.cargo/registry/**/*'
