plugins {
    id 'groovy'
    id 'java-library'
    id 'maven-publish'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven { url "https://nexus.ala.org.au/content/groups/public/" }
    maven { url "https://jitpack.io" }
}

java {
    sourceCompatibility = JavaVersion.toVersion("22")
    targetCompatibility = JavaVersion.toVersion("22")
}

dependencies {
    implementation localGroovy()
    api 'org.slf4j:slf4j-api:1.7.36'
    implementation 'com.google.guava:guava:33.2.1-jre'
    compileOnly project(':image-utils')
    testImplementation project(':image-utils')

    // The lopcode vips-ffm library
    implementation 'app.photofox.vips-ffm:vips-ffm-core:1.9.5'

    // Testing
    testImplementation 'org.spockframework:spock-core:2.3-groovy-3.0'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
    jvmArgs = [
        '--enable-preview',
        '--enable-native-access=ALL-UNNAMED'
    ]
    testLogging {
        showStandardStreams = true
        exceptionFormat = 'full'
    }
}

compileGroovy {
    options.compilerArgs << '--enable-preview'
}

tasks.withType(JavaCompile).configureEach {
    options.compilerArgs << '--enable-preview'
}
