[DEFAULT]
PRODUCT_COMPONENT=database
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${ENVIRONMENT}
DATABASE_STACK_FILE_PFIX = database
DATABASE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-${ENVIRONMENT}
AUTO_DEPLOY = false
SLACK_DEPLOY_NOTIFICATION = false
SLACK_ALERT_CHANNEL = testing-deployments

# RDS (Aurora PostgreSQL)
ADMIN_USER = dbmaster
BACKTRACK_WINDOW = 3600 # only applicable for MySQL, in seconds, between 0 - 259200 seconds (3 days)
BACKUP_RETENTION = 1 # number of days to retain automated backups, between 1 - 35 days
CREATE_REPLICA = false # create a read replica of the database
DB_INSTANCE_NAME = images-${ENVIRONMENT}
DB_ENGINE = aurora-postgresql # "aurora-mysql" or "aurora-postgresql"
ENGINE_MODE = provisioned # provisioned or serverlessv2
# supported versions for serverlessv2:
# https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.ServerlessV2.html
DB_VERSION = 18.3  # Aurora PostgreSQL version
# supported versions for provisioned:
# https://docs.aws.amazon.com/AmazonRDS/latest/AuroraMySQLReleaseNotes/AuroraMySQL.Updates.84Updates.html
# https://docs.aws.amazon.com/AmazonRDS/latest/AuroraPostgreSQLReleaseNotes/aurorapostgresql-release-calendar.html#aurorapostgresql.minor.versions.supported
DELETION_PROTECTION = false
DB_PARAM_GRP_FAMILY = aurora-postgresql18 # aurora-mysql8.4 for MySQL
INSTANCE_CLASS = db.t4g.medium  # Only used when ENGINE_MODE is provisioned
DATABASE_INSIGHTS_MODE = standard  # "standard" or "advanced"
# Performance insights is deprecated
# https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.PerfInsights.html
PERFORMANCE_INSIGHTS = false
ENHANCED_MONITORING = 0  # enhanced monitoring interval in seconds. Set to 0 to disable.
RDS_SNAPSHOT_RESTORE = false # set to the snapshot ARN, or false to disable
EXPORT_LOGS = false


[development]
# code pipeline
PIPELINE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-pipeline-${CLEAN_BRANCH}
DATABASE_STACK_NAME = ala-${PRODUCT_NAME}-${PRODUCT_COMPONENT}-${CLEAN_BRANCH}
SLACK_DEPLOY_NOTIFICATION = true
AUTO_DEPLOY = true

# RDS
DB_INSTANCE_NAME = images-${CLEAN_BRANCH}

[testing]
AUTO_DEPLOY = true

[staging]
# RDS
PERFORMANCE_INSIGHTS = true

[production]
DATABASE_INSIGHTS_MODE = advanced
DELETION_PROTECTION = true
PERFORMANCE_INSIGHTS = true
ENHANCED_MONITORING = 60
BACKUP_RETENTION = 30
CREATE_REPLICA = false
SLACK_ALERT_CHANNEL = deployments
ENGINE_MODE = provisioned
