---
info:
    app:
        name: 'image-service'
grails:
    serverURL: 'http://dev.ala.org.au:8080'
    profile: web
    codegen:
        defaultPackage: au.org.ala.images
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
    assets:
        bundle: false
    config:
        locations:
            - file:///data/image-service/config/image-service-config.properties
            - file:///data/image-service/config/image-service-config.yml
            - file:///data/image-service/config/image-service-config.groovy
    mime:
        use:
            accept:
                header: true
        disable:
            accept:
                header:
                    userAgents:
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            image:
              - image/jpeg
              - image/jpg
              - image/png
              - image/bmp
              - image/tiff
              - image/webp
              - image/apng
              - image/*
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        upload:
            maxFileSize: 200000000
            maxRequestSize: 200000000
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
    databinding:
        convertEmptyStringsToNull: false

server:
    contextPath: ''

environments:
    test:
        grails:
            config:
                locations:
                    - ~/image-service/test-image-service-config.yml

---
flyway:
    enabled: false
    baselineOnMigrate: true
    baselineVersion: 1
    outOfOrder: false
---
hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    cache:
        queries: true
        use_second_level_cache: false
        use_query_cache: true

dataSource:
    driverClassName: org.postgresql.Driver
    dbCreate: validate
    pooled: true
    jmxExport: true

environments:
    development:
        dataSource:
            driverClassName: "org.postgresql.Driver"
            logSql: false
            url: jdbc:postgresql://localhost/images?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
            username: "images"
            password: "images"
            type: "com.zaxxer.hikari.HikariDataSource"
            properties:
                maximumPoolSize: 30
                registerMbeans: true
                connectionTimeout: 5000
    test:
        grails:
            config:
                locations:
                    - ~/image-service/test-image-service-config.yml
        flyway:
            baselineOnMigrate: false
        dataSource:
            embeddedPostgres: true
            pooled: true
            jmxExport: true
            embeddedPort: 6543
            username: postgres
            password: postgres
            url: jdbc:postgresql://localhost:6543/postgres?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
        imageservice:
            imagestore:
                root: '/tmp/image-service/store'
                inbox: '/tmp/image-service/incoming'
            exportDir: '/tmp/image-service/exports'
    travis:
        flyway:
            baselineOnMigrate: false
        dataSource:
            embeddedPostgres: true
            pooled: true
            jmxExport: true
            embeddedPort: 6543
            username: postgres
            password: postgres
            url: jdbc:postgresql://localhost:6543/postgres?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
        imageservice:
            imagestore:
                root: '/home/travis/build/AtlasOfLivingAustralia/image-service/temp-store'
                inbox: '/home/travis/build/AtlasOfLivingAustralia/image-service/temp-incoming'
            exportDir: '/home/travis/build/AtlasOfLivingAustralia/image-service/temp-exports'

    production:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
        dataSource:
            dbCreate: validate
            driverClassName: org.postgresql.Driver
            url: jdbc:postgresql://localhost/images?autoReconnect=true&connectTimeout=0&useUnicode=true&characterEncoding=UTF-8
security:
    cas:
        appServerName: 'http://dev.ala.org.au:8080'
        uriFilterPattern: '/admin/.*,/admin,/admin/,/image/deleteImage/.*,/storageLocation,/storageLocation/.*'
        authenticateOnlyIfLoggedInPattern:  '/ws/createSubimage'
        bypass: false
        disableCAS: false

imageservice:
    imagestore:
        root: '/data/image-service/store'
        inbox: '/data/image-service/incoming'
        staging: '/data/image-service/store/staging'
    apache:
        root: '${grails.serverURL}${grails.contextPath}/store/'
        # space separated list
        multiple_roots: '${grails.serverURL}${grails.contextPath}/store/'
    exportDir: '/data/image-service/exports'
    thumbnail:
        size: 300

serverName: 'http://devt.ala.org.au:8080'

skin:
    layout: 'main'
    fluidLayout: true

quartz:
    autoStartup: true
    jdbcStore : false
    waitForJobsToCompleteOnShutdown: true
    exposeSchedulerInRepository: false
    props:
        scheduler:
            skipUpdateCheck: true

---
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: true
    jmx:
        enabled: true

placeholder:
    sound:
        thumbnail: "classpath:images/200px-Speaker_Icon.svg.png"
        large: "classpath:images/500px-Speaker_Icon.svg.png"
    document:
        thumbnail: "classpath:images/200px-Document_icon.svg.png"
        large: "classpath:images/500px-Document_icon.svg.png"
    missing:
        thumbnail: "classpath:images/200px-Document_icon.svg.png"

swagger:
    info:
        description: "API Documentation for Image Services"
        version: "2.0"
        title: "Image Service API"
        termsOfServices: "https://www.ala.org.au/who-we-are/terms-of-use/"
        contact:
            name: "ALA Support"
            url: "https://www.ala.org.au"
            email: "support@ala.org.au"
        license:
            name: "MPL 1.1"
            url: "https://www.mozilla.org/en-US/MPL/"
    schemes:
        - "HTTP"
    consumes:
        - "application/json"
    components:
        securitySchemes:
            apiKey:
                type: "apiKey"
                description: "Authentication via ALA apikey in request header"
                in: "header"
                name: "Authorization"

facets: ["recognisedLicence", "dataResourceUid", "creator.keyword", "imageSize", "fileType", "format", "dateUploadedYearMonth"]

analytics:
    credentialsJson: "/data/image-service/config/google-analytics.json"
    URL: "https://www.google-analytics.com"
    ID: "UA-4355440-1"
    baseURL: "https://www.googleapis.com/analytics/v3/data/ga"
    viewID: "ga:197294038"
    trackThumbnails: false
    trackLargeViewer: false
    trackDetailedView: false

elasticsearch:
  indexName: "images"
  host: "127.0.0.1"
  scheme: "http"
  port1: 9200
  port2: 9201
  maxFacetSize: 10000
  maxOffset: 10000
  maxPageSize: 200
  defaultPageSize: 10
  batchIndexSize: 1000

# Number of days to wait before purging completed batch jobs
purgeCompletedAgeInDays: 3

# The URLs to recognise as image service URL for the purposes of recognising incoming
# URLs for images (to avoid re-downloading the images)
imageServiceUrls: ["http://dev.ala.org.au:8080","https://images.ala.org.au"]

# External links
collectory:
    baseURL: "https://collections.ala.org.au"
biocache:
    baseURL: "https://biocache.ala.org.au"


